
version: '3'

services:
  app:
    build: .
    environment:
      NODE_ENV: development
    ports:
      - "3000:3000"

//for production

version: '3'

services:
  app:
    build: .
    environment:
      NODE_ENV: production
    ports:
      - "3000:3000"